### ISSUE TITLE
Can't use reference as parameter

### ISSUE THREAD

**Issue by gitmalong** [bwintertkb/retry_macro#1]
Thanks for this useful macro :)

When using something like `retry_async!(5, fetch, &address)` compilation fails with `no rules expected the token &`. Using an expression fn call does also not work.

**Comment by bwintertkb** [comment]
hey mate! Thanks for raising the issue and I'm glad you like the macro. Yeah these special tokens are not supported but what you can do is the following
```rust
let addr = &address;
retry_async!(5, fetch, addr);
```
Hope this helps!
(feel free to submit a PR if you would like to change this)

**Comment by gitmalong** [comment]
Yeah thanks this works fine. I can't make any promises regarding the PR but I let the issue open for now (of course you can change that).
